##' Calculate the callrate by locus
##'
##' SNP datasets generated by DArT have missing values primarily
##' arising from failure to call a SNP because of a mutation at one or
##' both of the the restriction enzyme recognition sites. The locus
##' metadata supplied by DArT has callrate included, but the call rate
##' will change when some individuals are removed from the
##' dataset. This function recalculates the callrate and places these
##' recalculated values in the appropriate place in the genlight
##' object.
##' @title Calculate Callrate
##' @param gl a genlight object
##' @return the modified genlight object
##' @author Arthur Georges (Post to \url{https://groups.google.com/d/forum/dartr})
utils.recalc.callrate <- function(gl) {

  gl@other$loc.metrics$CallRate <- 1-(glNA(gl,alleleAsUnit=FALSE))/nInd(gl)
  gl
}

